name: Testing Playwright and Allure
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright 
      run: npx playwright install --with-deps
    - name: Run all tests
      run: |
        npm run login_test
        npm run lost_pass_test
    - uses: actions/checkout@v2
      if: always()
      with:
        repository: chabanstas/Playwright
        ref:  allure-report
        path: ./allure-report
    - name: Generate Allure Report
      if: always()
      run: npm run generate_allure_report
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
    - name: Push to repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{ secrets.SECRET_TOKEN }}
      with:
        source-directory: 'allure-report'
        destination-github-username: 'chabanstas'
        destination-repository-name: 'Playwright'
        user-email: stanislav.chaban.02@gmail.com
        target-branch: allure-report


