name: Testing for Redmine with Playwright and Allure
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps
        npm install -g allure-commandline
    - name: Run tests
      run: |
        npm run login_test
        npm run lost_pass_test
        allure generate --clean
    - name: Copy previous Allure results
      if: always()
      run: |
        mkdir -p allure-results/history
        if [ -d "$HOME/allure-results" ]; then cp -R $HOME/allure-results/history allure-results/; fi
        cp -R allure-results/history allure-results/history-$(date '+%Y-%m-%d_%H-%M-%S')
    - name: Create new report
      run: |
        allure generate --clean
        echo "Allure report generated successfully!"
    - name: Push report to other branch
      uses: actions/github-script@v4
      with:
        script: |
          git config --global user.name "chabanstas"
          git config --global user.email "stanislav.chaban.02@gmail.com"
          git checkout -b allure-report
          git add .
          git commit -m "Add Allure report"
          git push origin allure-report
